fixes:
  - "/home/travis/build/IYP-Programer-Yeah/WaitFreeRingBufferUtilities/Projects/CMake/Build/include/WaitFreeRingBufferUtilities/::/home/travis/build/IYP-Programer-Yeah/WaitFreeRingBufferUtilities/WaitFreeRingBufferUtilities/Include"
