fixes:
  - "/home/travis/build/IYP-Programer-Yeah/WaitFreeRingBufferUtilities/Projects/CMake/Build/WaitFreeRingBufferUtilities/include/Iyp/WaitFreeRingBufferUtilities/::/home/travis/build/IYP-Programer-Yeah/WaitFreeRingBufferUtilities/WaitFreeRingBufferUtilities/Include"
