language: cpp
matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - gcc-5
            - g++-5
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

script:
  - sudo apt upgrade cmake
  - mkdir Projects/CMake/Build -p
  - cd Projects/CMake/Build
  - cmake --version
  - cmake .. -DCMAKE_INSTALL_PREFIX:PATH=./Artifact -DCMAKE_BUILD_TYPE=Debug -DBENCHMARK_ENABLE_TESTING=off -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage"
  - cmake --build .
  - cmake --install .
  - ./Artifact/bin/Test
  - echo "Building for coverage:"
  - cmake .. -DCMAKE_INSTALL_PREFIX:PATH=./Artifact -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-fprofile-arcs -ftest-coverage"
  - cmake --build .
  - cmake --install .
  - ls ./Artifact/bin/
  - ./Artifact/bin/Test
after_success:
  - bash <(curl -s https://codecov.io/bash)
